FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 AS builder
WORKDIR /go/src/github.com/openshift/azure-file-csi-driver
COPY . .
RUN make azurefile ARCH=$(go env GOARCH) && cp _output/$(go env GOARCH)/azurefileplugin .

# Use base image with azcopy installed
FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_5.0_azure-storage-azcopy-base
COPY --from=builder /go/src/github.com/openshift/azure-file-csi-driver/azurefileplugin /bin/azurefileplugin
RUN yum install -y cifs-utils util-linux nfs-utils e2fsprogs xfsprogs ca-certificates && yum clean all && rm -rf /var/cache/yum

LABEL description="Azure File CSI Driver"

ENTRYPOINT ["/bin/azurefileplugin"]
